version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mi_base_de_datos
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contrasena
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    command: --init-file /docker-entrypoint-initdb.d/data.sql